/*
 * (c) 2014 Rothsmith, LLC, All Rights Reserved
 */
// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders ArtifactGenerator Do not modify this
 * file See generator home page at:
 * http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */
package com.rothsmith.dao.def;

import java.util.List;
import java.util.Map;

import com.rothsmith.dao.db.IdxMetaData;
import com.rothsmith.dao.db.PKMetaData;
import com.rothsmith.dao.db.TblColMetaData;
import com.rothsmith.dao.db.TblMetaData;

@SuppressWarnings("PMD")
public class DefMetaDataBuilder
        extends
        DefMetaDataBuilderBase<DefMetaDataBuilder> {
	public static DefMetaDataBuilder daoMetaData() {
		return new DefMetaDataBuilder();
	}

	public DefMetaDataBuilder() {
		super(new DefMetaData());
	}

	public DefMetaData build() {
		return getInstance();
	}
}

@SuppressWarnings("PMD")
class DefMetaDataBuilderBase<T extends DefMetaDataBuilderBase<T>> {
	private DefMetaData instance;

	protected DefMetaDataBuilderBase(DefMetaData aInstance) {
		instance = aInstance;
	}

	protected DefMetaData getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public T withClassName(String aValue) {
		instance.setClassName(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withColumnMap(Map<Integer, TblColMetaData> aValue) {
		instance.setColumnMap(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withIndexMap(Map<String, List<IdxMetaData>> aValue) {
		instance.setIndexMap(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withOutputDir(String aValue) {
		instance.setOutputDir(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withPackageName(String aValue) {
		instance.setPackageName(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withPkMap(Map<Integer, PKMetaData> aValue) {
		instance.setPkMap(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withTblMetaData(TblMetaData aValue) {
		instance.setTblMetaData(aValue);

		return (T) this;
	}

	public TblMetaDataTblMetaDataBuilder withTblMetaData() {
		TblMetaData obj = new TblMetaData();

		withTblMetaData(obj);

		return new TblMetaDataTblMetaDataBuilder(obj);
	}

	@SuppressWarnings("unchecked")
	public T withTestOutputDir(String aValue) {
		instance.setTestOutputDir(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withTestPackageName(String aValue) {
		instance.setTestPackageName(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withUser(String aValue) {
		instance.setUser(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withSqlStmt(String aValue) {
		instance.setSqlStmt(aValue);

		return (T) this;
	}

	public class TblMetaDataTblMetaDataBuilder
	        extends
	        TblMetaDataBuilderBase<TblMetaDataTblMetaDataBuilder> {
		public TblMetaDataTblMetaDataBuilder(TblMetaData aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public T endTblMetaData() {
			return (T) DefMetaDataBuilderBase.this;
		}
	}

	public static class TblMetaDataBuilderBase<GeneratorT extends TblMetaDataBuilderBase<GeneratorT>> {
		private TblMetaData instance;

		protected TblMetaDataBuilderBase(TblMetaData aInstance) {
			instance = aInstance;
		}

		protected TblMetaData getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withRefGeneration(String aValue) {
			instance.setRefGeneration(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withRemarks(String aValue) {
			instance.setRemarks(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withSelfReferencingColName(String aValue) {
			instance.setSelfReferencingColName(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withTableCat(String aValue) {
			instance.setTableCat(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withTableName(String aValue) {
			instance.setTableName(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withTableSchem(String aValue) {
			instance.setTableSchem(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withTableType(String aValue) {
			instance.setTableType(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withTypeCat(String aValue) {
			instance.setTypeCat(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withTypeSchem(String aValue) {
			instance.setTypeSchem(aValue);

			return (GeneratorT) this;
		}
	}
}
